src/objects/CBAccount__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Account</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBDivision__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>{000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Division</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBFunction__c.object
<CustomObject>
    <fields>
        <fullName>CBAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>CBAccount__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBDivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Division</label>
        <referenceTo>CBDivision__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>CBVariable1__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 2</label>
        <referenceTo>CBVariable2__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 3</label>
        <referenceTo>CBVariable3__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 4</label>
        <referenceTo>CBVariable4__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 5</label>
        <referenceTo>CBVariable5__c</referenceTo>
        <relationshipLabel>CB Functions</relationshipLabel>
        <relationshipName>CB_Functions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>A{0000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>NFL1__c</fullName>
        <label>NFL1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFL2__c</fullName>
        <label>NFL2</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFL3__c</fullName>
        <label>NFL3</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFL4__c</fullName>
        <label>NFL4</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFL5__c</fullName>
        <label>NFL5</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NFLFormula__c</fullName>
        <label>NFL Formula</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&apos;Variable&apos;</defaultValue>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Variable</fullName>
                    <default>true</default>
                    <label>Variable</label>
                </value>
                <value>
                    <fullName>NFL</fullName>
                </value>
                <value>
                    <fullName>BLM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CB Function</label>
    <nameField>
        <label>CB Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable1__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>V{00000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Variable 1</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable2__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>V{00000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Variable 2</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable3__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>V{00000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Variable 3</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable4__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>V{00000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Variable 4</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 4</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable5__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>V{00000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <label>CB Variable 5</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 5</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBFunctionDomain.cls
/** 
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

*/

public with sharing class CBFunctionDomain extends fflib_SObjectDomain {
	public CBFunctionDomain(List<CBFunction__c> sObjectList) {
		super(sObjectList);
	}
	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new CBFunctionDomain(sObjectList);
		}
	}
	public override void onAfterInsert() {
		updateFunctionsTitle((List<CBFunction__c>) Records);
	}

	/**
	 * Prevent duplicating
	 */
	@TestVisible
	private static void updateFunctionsTitle(List<CBFunction__c> records) {
		fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
			new List<SObjectType>{
				CBFunction__c.SObjectType
			}
		);
		Set<Id> functionIds = new Set<Id>();
		for (CBFunction__c f : records) {
			if (String.isEmpty(f.Title__c)) {
				functionIds.add(f.Id);
			}
		}
		for (CBFunction__c f : [
				SELECT CBDivision__r.Name, CBAccount__r.Name, Index__c, Type__c,
						NFL1__c, NFL2__c, NFL3__c, NFL4__c, NFL5__c, NFLFormula__c,
						CBVariable1__c,CBVariable2__c,CBVariable3__c,CBVariable4__c,CBVariable5__c,
						CBVariable1__r.Name,CBVariable2__r.Name,CBVariable3__r.Name,CBVariable4__r.Name,CBVariable5__r.Name
				FROM CBFunction__c
				WHERE Id IN:functionIds
				WITH SECURITY_ENFORCED
		]) {
			if (f.Type__c == 'Variable') {
				f.Title__c = '#' + f.Index__c + '/'
						+ (f.CBDivision__c == null ? '' : '/' + f.CBDivision__r.Name)
						+ (f.CBAccount__c == null ? '' : '/' + f.CBAccount__r.Name)
						+ (f.CBVariable1__c == null ? '' : '/' + f.CBVariable1__r.Name)
						+ (f.CBVariable2__c == null ? '' : '/' + f.CBVariable2__r.Name)
						+ (f.CBVariable3__c == null ? '' : '/' + f.CBVariable3__r.Name)
						+ (f.CBVariable4__c == null ? '' : '/' + f.CBVariable4__r.Name)
						+ (f.CBVariable5__c == null ? '' : '/' + f.CBVariable5__r.Name);
			}
			if (f.Type__c == 'NFL') {
				f.Title__c = '#' + f.Index__c + '/' + f.NFLFormula__c;
			}
			uow.registerDirty(f);
		}
		uow.commitWork();
	}
}