src/objects/CBAccount__c.object
<CustomObject>
    <label>CB Account</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBAmount__c.object
<CustomObject>
    <fields>
        <fullName>CBBudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Budget Line</label>
        <referenceTo>CBBudgetLine__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CBAmounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBPeriod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>CBPeriod__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CB_Amounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CB Amount</label>
    <nameField>
        <label>CB Line Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBBudgetLine__c.object
<CustomObject>
    <fields>
        <fullName>CBAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>CBAccount__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBDivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Division</label>
        <referenceTo>CBDivision__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBDivisionLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>CBVariable1__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 2</label>
        <referenceTo>CBVariable2__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>CB Budget Line</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CBCube__c.object
<CustomObject>
    <fields>
        <fullName>Actual__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CBAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>CBAccount__c</referenceTo>
        <relationshipLabel>CB Cubes</relationshipLabel>
        <relationshipName>CB_Cubes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBDivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Division</label>
        <referenceTo>CBDivision__c</referenceTo>
        <relationshipLabel>CB Cubes</relationshipLabel>
        <relationshipName>CB_Cubes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBPeriod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>CBPeriod__c</referenceTo>
        <relationshipLabel>CB Cubes</relationshipLabel>
        <relationshipName>CB_Cubes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>CBVariable1__c</referenceTo>
        <relationshipLabel>CB Cubes</relationshipLabel>
        <relationshipName>CBCubes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 2</label>
        <referenceTo>CBVariable2__c</referenceTo>
        <relationshipLabel>CB Cubes</relationshipLabel>
        <relationshipName>CBCubes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Cube</label>
    <nameField>
        <label>CBCube Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Cubes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CBDivision__c.object
<CustomObject>
    <label>CB Division</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBInvoice__c.object
<CustomObject>
    <fields>
        <fullName>CBAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>CBAccount__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBDivision__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Division</label>
        <referenceTo>CBDivision__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>CBPeriod__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>CBVariable1__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Variable 2</label>
        <referenceTo>CBVariable2__c</referenceTo>
        <relationshipLabel>CB Invoices</relationshipLabel>
        <relationshipName>CB_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <summarizedField>CBInvoiceLine__c.Amount__c</summarizedField>
        <summaryForeignKey>CBInvoiceLine__c.CBInvoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CB Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBPeriod__c.object
<CustomObject>
    <label>CB Period</label>
    <nameField>
        <label>CB Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable1__c.object
<CustomObject>
    <label>CB Variable 1</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable2__c.object
<CustomObject>
    <label>CB Variable 2</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBLightCubeRefreshTriggerService.cls
/**
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

The class serves to update reporting data on the fly (Modeling rules are not in use)
 */


public with sharing class CBLightCubeRefreshTriggerService {

	private static Map<String, CBCube__c> cubeMap = new Map<String, CBCube__c>();// key is period+Division+Account+Var1+Var2

	public static void refreshAllCBCubes() {
		deleteAllOldCBCubes();
		generateCubesFromCBBudgetLines();
		generateCubesFromCBInvoices();
		insert(cubeMap.values());
	}

	private static void deleteAllOldCBCubes() {
		delete [SELECT Id FROM CBCube__c];
	}

	public static void generateCubesFromCBBudgetLines() {
		List<CBBudgetLine__c> allBudgetLines = new CBBudgetLineSelector().getBudgetLines('');
		for (CBBudgetLine__c bl : allBudgetLines) {
			for (CBAmount__c amount : bl.CBAmounts__r) {
				String key = getCubeKeyFromBL(bl, amount);
				CBCube__c cbCube = cubeMap.get(key);
				if (cbCube == null) {
					cbCube = getNewCBCubeFromBL(bl, amount);
					cubeMap.put(key, cbCube);
				}
				cbCube.Budget__c += amount.Value__c;
			}
		}
	}

	public static void generateCubesFromCBInvoices() {
		for (CBInvoice__c invoice : [SELECT Id, CBPeriod__c, CBDivision__c, CBAccount__c, CBVariable1__c, CBVariable2__c, Total__c FROM CBInvoice__c]) {
			String key = getCubeKeyFromInvoice(invoice);
			CBCube__c cbCube = cubeMap.get(key);
			if (cbCube == null) {
				cbCube = getNewCBCubeFromInvoice(invoice);
				cubeMap.put(key, cbCube);
			}
			cbCube.Actual__c += invoice.Total__c;
		}
	}

	private static String getCubeKeyFromBL(CBBudgetLine__c bl, CBAmount__c amount) {
		return amount.CBPeriod__c + '' + bl.CBDivision__c + bl.CBAccount__c + bl.CBVariable1__c + bl.CBVariable2__c;
	}
	private static String getCubeKeyFromInvoice(CBInvoice__c invoice) {
		return invoice.CBPeriod__c + '' + invoice.CBDivision__c + invoice.CBAccount__c + invoice.CBVariable1__c + invoice.CBVariable2__c;
	}
	private static CBCube__c getNewCBCubeFromBL(CBBudgetLine__c bl, CBAmount__c amount) {
		return new CBCube__c(Name = 'CBLight Cube', CBPeriod__c = amount.CBPeriod__c, CBDivision__c = bl.CBDivision__c, Budget__c = 0, Actual__c = 0,
				CBVariable1__c = bl.CBVariable1__c, CBVariable2__c = bl.CBVariable2__c, CBAccount__c = bl.CBAccount__c);
	}
	private static CBCube__c getNewCBCubeFromInvoice(CBInvoice__c invoice) {
		return new CBCube__c(Name = 'CBLight Cube', CBPeriod__c = invoice.CBPeriod__c, CBDivision__c = invoice.CBDivision__c, Budget__c = 0, Actual__c = 0,
				CBVariable1__c = invoice.CBVariable1__c, CBVariable2__c = invoice.CBVariable2__c, CBAccount__c = invoice.CBAccount__c);
	}
}