src/objects/CBAccount__c.object
<CustomObject>
    <fields>
        <fullName>CBAccountType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Account Type</label>
        <referenceTo>CBAccountType__c</referenceTo>
        <relationshipLabel>CB Accounts</relationshipLabel>
        <relationshipName>CBAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Account</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBAccountType__c.object
<CustomObject>
    <fields>
        <fullName>CBStyle__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Style</label>
        <referenceTo>CBStyle__c</referenceTo>
        <relationshipLabel>CB Styles</relationshipLabel>
        <relationshipName>CB_Styles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Account Type</label>
    <nameField>
        <label>CB Account Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Account Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBAmount__c.object
<CustomObject>
    <fields>
        <fullName>CBBudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Budget Line</label>
        <referenceTo>CBBudgetLine__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CBAmounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBBudgetYear__c</fullName>
        <formula>CBPeriod__r.CBBudgetYear__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CB Budget Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CBPeriod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>CBPeriod__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CB_Amounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBStyle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Style</label>
        <referenceTo>CBStyle__c</referenceTo>
        <relationshipLabel>CB Amounts</relationshipLabel>
        <relationshipName>CB_Style</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Amount</label>
    <nameField>
        <label>CB Line Amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBBudgetLine__c.object
<CustomObject>
    <fields>
        <fullName>CBAccountType__c</fullName>
        <formula>CBAccount__r.CBAccountType__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CBAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Account</label>
        <referenceTo>CBAccount__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBBudgetYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Budget Year</label>
        <referenceTo>CBBudgetYear__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CB_Budget_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBDivision__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Division</label>
        <referenceTo>CBDivision__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBDivisionLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 1</label>
        <referenceTo>CBVariable1__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 2</label>
        <referenceTo>CBVariable2__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBVariable3__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Variable 3</label>
        <referenceTo>CBVariable3__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 1</label>
        <referenceTo>CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 2</label>
        <referenceTo>CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL3__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 3</label>
        <referenceTo>CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL4__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 4</label>
        <referenceTo>CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NFL5__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Non-Financial Library 5</label>
        <referenceTo>CBNonFinancialLibrary__c</referenceTo>
        <relationshipLabel>CB Budget Lines</relationshipLabel>
        <relationshipName>CBBudgetLines5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Budget Line</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CBBudgetYear__c.object
<CustomObject>
    <label>CB Budget Year</label>
    <nameField>
        <label>CB Budget Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Budget Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBClusterRule__c.object
<CustomObject>
    <label>CB Cluster Rule</label>
    <nameField>
        <label>CB Cluster Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Cluster Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBDivision__c.object
<CustomObject>
    <label>CB Division</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBLayer__c.object
<CustomObject>
    <label>CB Layer</label>
    <nameField>
        <label>CB Layer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBNonFinancialLibrary__c.object
<CustomObject>
    <fields>
        <fullName>Layer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Layer</label>
        <referenceTo>CBLayer__c</referenceTo>
        <relationshipName>NonfinancialLibraries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Non-Financial Library</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Non-Financial Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CBPeriod__c.object
<CustomObject>
    <fields>
        <fullName>CBBudgetYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Budget Year</label>
        <referenceTo>CBBudgetYear__c</referenceTo>
        <relationshipLabel>CB Periods</relationshipLabel>
        <relationshipName>CBPeriods</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Period</label>
    <nameField>
        <label>CB Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBStyle__c.object
<CustomObject>
    <label>CB Style</label>
    <nameField>
        <label>CBStyle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable1__c.object
<CustomObject>
    <label>CB Variable 1</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable2__c.object
<CustomObject>
    <label>CB Variable 2</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBVariable3__c.object
<CustomObject>
    <label>CB Variable 3</label>
    <nameField>
        <label>CB Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Variables 3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBBudgetLinePageControllerTest.cls
/**
 * This test class covers the CBBudgetLinePageController, CBBudgetLineService,
 * CBNonFinancialLibrarySelector, CBBudgetLineDomain, CBBudgetLineSelector classes
 */
@IsTest
public class CBBudgetLinePageControllerTest {
	@IsTest
	public static void testGetBudgetLinesServer() {
		CBDataFactoryTest.createOrgVariable();
		List<CBAmount__c> amounts = CBDataFactoryTest.createAmounts(1);
		List<CBBudgetLine__c> blList = [
				SELECT Id, Name, CBBudgetYear__c, CBDivision__c, CBAccount__c, CBVariable1__c, CBVariable2__c, CBVariable3__c
				FROM cblight__CbBudgetLine__c
		];
		Map<String, String> params = new Map<String, String>();
		params.put('cblight__CBBudgetYear__c', blList[0].CBBudgetYear__c);
		params.put('approach', 'bottom-up');
		List<CBBudgetLine__c> actualList = CBBudgetLinePageController.getBudgetLinesServer(params);
		System.assertEquals(blList.size(), actualList.size(), 'size not equals');
	}

	@IsTest
	public static void testSaveBudgetLineServer() {
		User adminUser = CBTestService.createAdminUser();
		System.runAs(adminUser) {
			List<CBAmount__c> amounts = CBDataFactoryTest.createAmounts(2);
			List<CBBudgetLine__c> blList = [SELECT Id, NFL1__c, NFL2__c, NFL3__c, NFL4__c, NFL5__c FROM cblight__CBBudgetLine__c];
			List<CBBudgetLine__c> actualList = CBBudgetLinePageController.saveBudgetLineServer(blList[0], amounts);
			System.assertEquals(blList.size(), actualList.size(), 'size not equals');
		}
	}

	@IsTest
	public static void testGetPeriodsServer() {
		List<CBBudgetLine__c> blList = CBDataFactoryTest.createBudgetLines(1);
		List<CBPeriod__c> actualList = CBBudgetLinePageController.getPeriodsServer();
		System.assertEquals(blList.size(), actualList.size(), 'size not equals');
	}

	@IsTest
	public static void testDeleteBudgetLineServer() {
		List<CBBudgetLine__c> blList = CBDataFactoryTest.createBudgetLines(3);
		CBBudgetLinePageController.deleteBudgetLineServer(blList[0].Id);
		List<CBBudgetLine__c> actualList = [SELECT Id FROM cblight__CBBudgetLine__c WHERE Id = :blList[0].Id];
		System.assert(actualList.isEmpty(), 'list is not empty');
	}

	@IsTest
	public static void testGetStylesForAccountTypesServer() {
		List<CBBudgetLine__c> blList = CBDataFactoryTest.createBudgetLines(3);
		List<CBStyle__c> expectedStyles = [SELECT Id, Name FROM cblight__CBStyle__c];
		List<CBStyle__c> actualList = CBBudgetLinePageController.getStylesForAccountTypesServer();
		System.assertEquals(expectedStyles[0].Name, actualList[0].Name, 'names not equals');
	}

	@IsTest
	public static void testGetAccTypesWithStylesNamesServer() {
		List<CBAccountType__c> accTypes = CBDataFactoryTest.createAccountTypes(10);
		List<CBStyle__c> styles = CBDataFactoryTest.createStyles(10, 'Budget Line');
		List<CBStyle__c> expectedStyles = [SELECT Id, Name FROM cblight__CBStyle__c];
		List<CBAccountType__c> actualList = CBBudgetLinePageController.getAccTypesWithStylesNamesServer();
		System.debug(actualList);
		System.assertEquals(expectedStyles[0].Id, actualList[0].cblight__CBStyle__c, 'style id is not equals');
	}

	@IsTest
	public static void testGetStylesRecordsServer() {
		List<CBStyle__c> styles = CBDataFactoryTest.createStyles(10, 'Cluster Rule');
		List<CBStyle__c> expectedStyles = [SELECT Id, Name FROM cblight__CBStyle__c];
		List<CBStyle__c> actualList = CBBudgetLinePageController.getStylesRecordsServer();
		System.assertEquals(expectedStyles[0].Name, actualList[0].Name, 'names not equals');
	}

	@IsTest
	public static void testGetNonFinancialLibrariesServer() {
		List<CBNonFinancialLibrary__c> listNFL = CBDataFactoryTest.createNonFinancialLibraries(1);
		List<CBNonFinancialLibrary__c> actualList = CBBudgetLinePageController.getNonFinancialLibrariesServer();
		System.assertEquals(listNFL.size(), actualList.size(), 'size not equals');
	}

	@IsTest
	public static void testGetClusterRuleServer() {
		List<CBClusterRule__c> clRules = CBDataFactoryTest.createClusterRules(1);
		Map<String, String> params = new Map<String, String>();
		params.put('cblight__CBClusterRule__c', clRules[0].Id);
		CBClusterRule__c actualClRule = CBBudgetLinePageController.getClusterRuleServer(params);
		System.assertEquals(clRules[0].Id, actualClRule.Id, 'ids not equals');
	}

	@IsTest
	public static void testGetSelectOptionsServer() {
		List<CBBudgetLine__c> blList = CBDataFactoryTest.createBudgetLines(1);
		Map<String, List<CBSO>> actualMap = CBBudgetLinePageController.getSelectOptionsServer();
		System.assert(!actualMap.isEmpty(), 'map is not empty');
	}

	@IsTest
	public static void testSetLimit() {
		Integer limitCount = 100;
		CBBudgetLineSelector bls = new CBBudgetLineSelector().setLimit(limitCount);
		System.assert(limitCount != null && limitCount > 0, 'limit was set');
	}

	@IsTest
	public static void testSetFilter() {
		String filter = 'Name LIKE \'%Test%\'';
		CBBudgetLineSelector bls = new CBBudgetLineSelector().setFilter(filter);
		System.assert(!String.isBlank(filter), 'filter was set');
	}

	@IsTest
	public static void testQuery() {
		List<CBBudgetLine__c> blList = CBDataFactoryTest.createBudgetLines(1);
		List<CBBudgetLine__c> actualList = new CBBudgetLineSelector().query();
		System.assertEquals(blList.size(), actualList.size(), 'size not equals');
	}

	@IsTest
	static void testGetLibrariesFromBudgetLineServer() {
		CBLayer__c l = new CBLayer__c(Name = 'test');
		insert l;
		List<CBNonFinancialLibrary__c> nflList = new List<CBNonFinancialLibrary__c>();
		CBNonFinancialLibrary__c nfl1 = new CBNonFinancialLibrary__c(Name = 'test1', Layer__c = l.Id);
		CBNonFinancialLibrary__c nfl2 = new CBNonFinancialLibrary__c(Name = 'test2', Layer__c = l.Id);
		nflList.add(nfl1);
		nflList.add(nfl2);
		insert nflList;
		List<String> idList = new List<String>{
				nfl1.Id, nfl2.Id
		};
		List<CBNonFinancialLibrary__c> nflList2 = CBBudgetLinePageController.getLibrariesFromBudgetLineServer(idList);
		System.assertEquals(nflList.size(), nflList2.size(), 'size not equals');
	}

	@IsTest
	public static void testGlobalSearch() {
		CBDataFactoryTest.createOrgVariable();
		List<CBAmount__c> amounts = CBDataFactoryTest.createAmounts(1);
		List<CBBudgetLine__c> BLList = CBBudgetLineGlobalSearchService.getBudgetLinesBySearchServer('1000');
		BLList = CBBudgetLineGlobalSearchService.getBudgetLinesBySearchServer('Test');
		System.assert(BLList.size() > 0, 'Global search do not work');
	}
}