src/objects/CBCalculationRule__c.object
<CustomObject>
    <fields>
        <fullName>CBFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Folder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CBFolder__c.FolderType__c</field>
                <operation>equals</operation>
                <value>Calculation Rule</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CBFolder__c</referenceTo>
        <relationshipLabel>CB Calculation Rule Folders</relationshipLabel>
        <relationshipName>CB_CR_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Calculation Rule</label>
    <nameField>
        <label>CB Calculation Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Calculation Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBFolder__c.object
<CustomObject>
    <fields>
        <fullName>CBFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Folder</label>
        <referenceTo>CBFolder__c</referenceTo>
        <relationshipLabel>CB Folders</relationshipLabel>
        <relationshipName>CB_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FolderType__c</fullName>
        <label>Folder Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modeling Rule</fullName>
                </value>
                <value>
                    <fullName>Calculation Rule</fullName>
                </value>
                <value>
                    <fullName>Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CB Folder</label>
    <nameField>
        <label>CB Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBModelingRuleGroup__c.object
<CustomObject>
    <description>Parent record for several Modeling Rules</description>
    <fields>
        <fullName>CBFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Folder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CBFolder__c.FolderType__c</field>
                <operation>equals</operation>
                <value>Modeling Rule</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CBFolder__c</referenceTo>
        <relationshipLabel>CB Modeling Rule Group Folders</relationshipLabel>
        <relationshipName>CB_MRG_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Modeling Rule Group</label>
    <nameField>
        <label>CB Modeling Rule Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Rule Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBReport__c.object
<CustomObject>
    <fields>
        <fullName>CBFolder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Folder</label>
        <referenceTo>CBFolder__c</referenceTo>
        <relationshipLabel>CB Report Folders</relationshipLabel>
        <relationshipName>CB_R_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Report</label>
    <nameField>
        <label>CB Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBFolderController.cls
/**
 Created by Alex JR on 08/18/2022.
 Copyright (c) 2022, CloudBudget, Inc.
 All rights reserved.
 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 * Neither the name of the CloudBudget, Inc. nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 OF THE POSSIBILITY OF SUCH DAMAGE.

 */
public with sharing class CBFolderController {
	private static final Map<String, SobjectType> STMAP = new Map<String, SobjectType>{
		'Modeling Rule' => CBModelingRuleGroup__c.SobjectType,
		'Calculation Rule' => CBCalculationRule__c.SobjectType,
		'Report' => CBReport__c.SobjectType
	};

	@AuraEnabled
	public static List<CBFolder__c> getFoldersByTypeServer(String type) {
		try {
			type = CBUtils.refineStr(type);
			return new CBSobjectSelector(CBFolder__c.sObjectType).getSobjects('FolderType__c = \'' + type + '\'');
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
	@AuraEnabled
	public static CBFolder__c getFolderByNameServer(String folderName) {
		folderName = CBUtils.refineStr(folderName);
		List<CBFolder__c> folderList = (List<CBFolder__c>) new CBSobjectSelector(CBFolder__c.sObjectType).getSobjects('Name = \'' + folderName + '\'');
		if (folderList.size() > 0) {
			return folderList[0];
		} else {
			return null;
		}
	}
	@AuraEnabled
	public static CBFolder__c getFolderByIdServer(String folderId) {
		List<CBFolder__c> folderList = (List<CBFolder__c>) new CBSobjectSelector(CBFolder__c.sObjectType).getSobjects('Id = \'' + folderId + '\'');
		if (folderList.size() > 0) {
			return folderList[0];
		} else {
			return null;
		}
	}

	@AuraEnabled
	public static String getRecordsOfFolderServer(String folderId, String folderType) {
		String result;
		folderType = CBUtils.refineStr(folderType);
		SobjectType st = STMAP.get(folderType);
		String filter = '';
		if (folderId != null && folderId != 'null') {
			filter = 'CBFolder__c = \'' + folderId + '\'';
		} else {
			filter = 'CBFolder__c = null';
		}
		if (st != null) {
			result = JSON.serialize(new CBSobjectSelector(st).getSobjects(filter));
		}
		return result;
	}

	@AuraEnabled
	public static void deleteFolderServer(Id folderId) {
		CBFolder__c folder = getFolderByIdServer(folderId);
		if (folder != null) {
			fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<SObjectType>{ CBFolder__c.SObjectType });
			uow.registerDeleted(folder);
			uow.commitWork();
		}
	}
}