src/objects/CBClusterRule__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <displayFormat>R-{00}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Level1__c</fullName>
        <defaultValue>&apos;cblight__CBDivision__c&apos;</defaultValue>
        <description>The name of sObject</description>
        <label>Level1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level2__c</fullName>
        <description>The name of the second sObject that should group the clusters</description>
        <label>Level2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level3__c</fullName>
        <description>The name of the second sObject that should group the clusters</description>
        <label>Level3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level4__c</fullName>
        <description>The name of the second sObject that should group the clusters</description>
        <label>Level4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level5__c</fullName>
        <description>The name of the second sObject that should group the clusters</description>
        <label>Level5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CB Cluster Rule</label>
    <nameField>
        <label>CB Cluster Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Cluster Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBClusterRuleSelector.cls
/** 
Created by Alex JR on 10/23/2021.
Copyright (c) 2021, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

Selector for the Cluster Rule sObject
 */
public with sharing class CBClusterRuleSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
				CBClusterRule__c.Id,
				CBClusterRule__c.Index__c,
				CBClusterRule__c.Name,
				CBClusterRule__c.Level1__c,
				CBClusterRule__c.Level2__c,
				CBClusterRule__c.Level3__c,
				CBClusterRule__c.Level4__c,
				CBClusterRule__c.Level5__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return CBClusterRule__c.sObjectType;
	}

	public override String getOrderBy() {
		return 'Name';
	}

	public List<CBClusterRule__c> getClusterRules(String recordId) {
		fflib_QueryFactory query = newQueryFactory();
		if (!String.isBlank(recordId)) {
			query.setCondition('Id = \'' + recordId + '\'');
		}
		return Database.query(query.toSOQL());
	}
}