src/objects/CBLayer__c.object
<CustomObject>
    <label>CB Layer</label>
    <nameField>
        <label>CB Layer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBNonFinancialItem__c.object
<CustomObject>
    <fields>
        <fullName>CBPeriod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>CBPeriod__c</referenceTo>
        <relationshipLabel>CB Non-Financial Items</relationshipLabel>
        <relationshipName>NonFinancialItems</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NonFinancialLibrary__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Non-Financial Library</label>
        <referenceTo>CBNonFinancialLibrary__c</referenceTo>
        <relationshipName>NonFinancialItems</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Non-Financial Item</label>
    <nameField>
        <displayFormat>NFI-{000000}</displayFormat>
        <label>Index</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CB Non-Financial Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBNonFinancialLibrary__c.object
<CustomObject>
    <fields>
        <fullName>Layer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Layer</label>
        <referenceTo>CBLayer__c</referenceTo>
        <relationshipName>NonfinancialLibraries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CB Non-Financial Library</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Non-Financial Libraries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CBPeriod__c.object
<CustomObject>
    <label>CB Period</label>
    <nameField>
        <label>CB Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBNonFinancialLibraryPageControllerTest.cls
/** 
Created by Aleksei Volkov on 08/17/2022.
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

This test class covers the CBNonFinancialLibraryPageController, CBNonFinancialItemSelector classes
 */
@IsTest
public class CBNonFinancialLibraryPageControllerTest {
    
    @IsTest
    public static void testGetNonFinLibraryServer() {
        List<CBNonFinancialLibrary__c> nflList = CBDataFactoryTest.createNonFinancialLibraries(1);
        CBNonFinancialLibrary__c actualNFL = CBNonFinancialLibraryPageController.getNonFinLibraryServer(nflList[0].Id);
        System.assertEquals(nflList[0].Id, actualNFL.Id, 'IDs are not equals');
    }

    @IsTest
    public static void testGetAllPeriodsServer() {
        List<CBPeriod__c> expectedPeriods = CBDataFactoryTest.createPeriods(3);
        List<CBPeriod__c> actualPeriods = CBNonFinancialLibraryPageController.getAllPeriodsServer();
        Assert.areEqual(expectedPeriods.size(), actualPeriods.size(), 'The number of periods is not the same');
    }

    @IsTest
    public static void testSaveNonFinancialLibServer() {
        List<CBLayer__c> layers = CBDataFactoryTest.createLayers(1);
        CBNonFinancialLibrary__c nfl = new CBNonFinancialLibrary__c(Name = 'Test NFL', Layer__c = layers[0].Id);
        CBDataFactoryTest.createPeriods(1);
        CBNonFinancialLibraryPageController.saveNonFinancialLibServer(nfl, null);
        List<CBNonFinancialItem__c> relatedItems = [SELECT Id, NonFinancialLibrary__c FROM cblight__CBNonFinancialItem__c WHERE NonFinancialLibrary__c =: nfl.Id];
        CBNonFinancialLibraryPageController.saveNonFinancialLibServer(nfl, relatedItems);

        Assert.areEqual(nfl.Id, relatedItems[0].NonFinancialLibrary__c, 'IDs are not equals');
    }

    @IsTest
    public static void testGetNonFinancialItemsByFilter() {
        Integer periodsNum = 4;
        CBDataFactoryTest.createPeriods(periodsNum);
        List<CBLayer__c> layers = CBDataFactoryTest.createLayers(1);
        CBNonFinancialLibrary__c nfl = new CBNonFinancialLibrary__c(Name = 'Test NFL', Layer__c = layers[0].Id);
        CBNonFinancialLibraryPageController.saveNonFinancialLibServer(nfl, null);
        String filter = 'NonFinancialLibrary__c = \'' + nfl.Id + '\'';
        List<CBNonFinancialItem__c> actualNFIList = new CBNonFinancialItemSelector().getNonFinancialItemsByFilter(filter);

        Assert.areEqual(periodsNum, actualNFIList.size(), 'The number of NFL items not equal to the number of periods');
        Assert.areEqual(nfl.Id, actualNFIList[0].NonFinancialLibrary__c, 'Items are not related to current NFL');
    }

}