src/objects/CBMapping__c.object
<CustomObject>
    <label>CB Mapping</label>
    <nameField>
        <label>CB Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBModelingLine__c.object
<CustomObject>
    <description>Mapping one object field to another</description>
    <fields>
        <fullName>CBModelingRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Modeling Rule</label>
        <referenceTo>CBModelingRule__c</referenceTo>
        <relationshipLabel>CB Modeling Lines</relationshipLabel>
        <relationshipName>CBModelingLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Modeling Line</label>
    <nameField>
        <label>CB Modeling Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBModelingRule__c.object
<CustomObject>
    <description>Rule for converting one data type to another</description>
    <label>CB Modeling Rule</label>
    <nameField>
        <label>CB Modeling Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBModelingLineServiceTest.cls
@isTest
global class CBModelingLineServiceTest {
	@isTest
	public static void crPredModLinesWithoutMappingInternalTest() {
		//Given
		List<CBModelingRule__c> modelingRules = CBDataFactoryTest.createModelingRules(1);
		String mrId = modelingRules[0].Id;

		//When
		CBModelingLineService.createPredefinedModelingLines(mrId);

		//Then
		CBModelingRule__c mr = new CBModelingRuleSelector().getModelingRuleById(mrId);
		List<CBModelingLine__c> existingLines = mr.cblight__CBModelingLines__r;
		System.assertEquals(11, existingLines.size(), 'modeling line list size is not correct');
	}
	
	@isTest
	public static void crPredModLinesWithMappingExternalTest() {
		//Given
		CBMapping__c mapping = CBDataFactoryTest.createDivisionCBMapping();
		mapping = CBDataFactoryTest.createPeriodCBMapping();
		mapping = CBDataFactoryTest.createAcntCBMapping();
		List<CBModelingRule__c> modelingRules = CBDataFactoryTest.createModelingRules(1);
		String mrId = modelingRules[0].Id;

		//When
		CBModelingLineService.createPredefinedModelingLines(mrId);

		//Then
		CBModelingRule__c mr = new CBModelingRuleSelector().getModelingRuleById(mrId);
		List<CBModelingLine__c> existingLines = mr.cblight__CBModelingLines__r;
		System.assertEquals(11, existingLines.size(), 'modeling line list size is not correct');
	}
}