src/objects/CBModelingLine__c.object
<CustomObject>
    <description>Mapping one object field to another</description>
    <fields>
        <fullName>CBModelingRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Modeling Rule</label>
        <referenceTo>CBModelingRule__c</referenceTo>
        <relationshipLabel>CB Modeling Lines</relationshipLabel>
        <relationshipName>CBModelingLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CB Modeling Line</label>
    <nameField>
        <label>CB Modeling Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBModelingRule__c.object
<CustomObject>
    <description>Rule for converting one data type to another</description>
    <fields>
        <fullName>CBModelingRuleGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Modeling Rule Group</label>
        <referenceTo>CBModelingRuleGroup__c</referenceTo>
        <relationshipLabel>CB Modeling Rules</relationshipLabel>
        <relationshipName>CBModelingRules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ComplexFilterCondition__c</fullName>
        <label>Complex Filter Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>KeyFields__c</fullName>
        <label>KeyFields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General</fullName>
                    <default>true</default>
                    <label>General</label>
                </value>
                <value>
                    <fullName>Deleting</fullName>
                </value>
                <value>
                    <fullName>Replacing</fullName>
                </value>
                <value>
                    <fullName>Zeroing amounts</fullName>
                </value>
                <value>
                    <fullName>Mass Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MultilevelResult__c</fullName>
        <formula>ResultRecordChildType__c != null</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MultilevelResult</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MultilevelSource__c</fullName>
        <formula>SourceRecordChildType__c != null</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Multilevel Source</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResultChildFilter__c</fullName>
        <label>Result Child Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResultParentFilter__c</fullName>
        <label>Result Parent Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResultRecordChildType__c</fullName>
        <label>Result Record Child Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultRecordParentType__c</fullName>
        <label>Result Record Parent Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceChildFilter__c</fullName>
        <label>Source Child Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SourceParentFilter__c</fullName>
        <label>Source Parent Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SourceRecordChildType__c</fullName>
        <label>Source Record Child Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceRecordParentType__c</fullName>
        <description>The name of the source sObject type</description>
        <label>Source Record Parent Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StoreDrillDown__c</fullName>
        <formula>CBModelingRuleGroup__r.StoreDrillDown__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Drill Down</label>
        <type>Checkbox</type>
    </fields>
    <label>CB Modeling Rule</label>
    <nameField>
        <label>CB Modeling Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBModelingRuleGroup__c.object
<CustomObject>
    <description>Parent record for several Modeling Rules</description>
    <fields>
        <fullName>StoreDrillDown__c</fullName>
        <defaultValue>true</defaultValue>
        <description>True if DrillDown needed</description>
        <inlineHelpText>True if DrillDown needed</inlineHelpText>
        <label>Store Drill Down</label>
        <type>Checkbox</type>
    </fields>
    <label>CB Modeling Rule Group</label>
    <nameField>
        <label>CB Modeling Rule Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Rule Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBModelingRuleSelector.cls
/**
 Copyright (c) 2021, CloudBudget, Inc.
 All rights reserved.
 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 * Neither the name of the CloudBudget, Inc. nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 OF THE POSSIBILITY OF SUCH DAMAGE.

 Selector for the ModelingRule sObject
 */
public with sharing class CBModelingRuleSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
				CBModelingRule__c.CBModelingRuleGroup__c,
				CBModelingRule__c.ComplexFilterCondition__c,
				CBModelingRule__c.Description__c,
				CBModelingRule__c.Id,
				CBModelingRule__c.KeyFields__c,
				CBModelingRule__c.Mode__c,
				CBModelingRule__c.MultilevelResult__c,
				CBModelingRule__c.MultilevelSource__c,
				CBModelingRule__c.Name,
				CBModelingRule__c.cblight__PeriodShift__c,
				CBModelingRule__c.SourceChildFilter__c,
				CBModelingRule__c.SourceParentFilter__c,
				CBModelingRule__c.ResultChildFilter__c,
				CBModelingRule__c.ResultParentFilter__c,
				CBModelingRule__c.ResultRecordParentType__c,
				CBModelingRule__c.ResultRecordChildType__c,
				CBModelingRule__c.SourceRecordParentType__c,
				CBModelingRule__c.SourceRecordChildType__c,
				CBModelingRule__c.StoreDrillDown__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return CBModelingRule__c.sObjectType;
	}

	public override String getOrderBy() {
		return 'Name';
	}
	/**
	 * @param recordId id of needed Modeling Rule
	 * @return modeling rule with list of its modeling lines
	 */
	public CBModelingRule__c getModelingRuleById(String recordId) {
		if (recordId == null) {
			return null;
		}
		fflib_QueryFactory query = newQueryFactory();
		if (!String.isBlank(recordId)) {
			query.setCondition('Id = \'' + recordId + '\'');
		}
		new CBModelingLineSelector().addQueryFactorySubSelect(query, 'cblight__CBModelingLines__r');
		return Database.query(query.toSOQL());
	}
	/**
	 * @param recordId (String): id of needed Modeling Rule Group
	 *
	 * @return List<CBModelingRule__c>: List of the Rules records order by Modeling Rule Group
	 */
	public List<CBModelingRule__c> getModelingRulesByGroupId(String recordId) {
		fflib_QueryFactory query = newQueryFactory();
		if (!String.isBlank(recordId)) {
			query.setCondition('cblight__CBModelingRuleGroup__c = \'' + recordId + '\'');
		}
		new CBModelingLineSelector().addQueryFactorySubSelect(query, 'cblight__CBModelingLines__r');
		return Database.query(query.toSOQL());
	}
	/**
	 * @param recordIdSet (Set<String>): Set of record Id
	 *
	 * @return List<CBModelingRule__c: List of the Rules records order by Group Set Id
	 */
	public List<CBModelingRule__c> getModelingRulesByGroupSet(Set<String> recordIdSet) {
		fflib_QueryFactory query = newQueryFactory();
		if (recordIdSet.size() > 0) {
			query.setCondition('cblight__CBModelingRuleGroup__c IN ' + CBUtils.getFormattedINQuery(recordIdSet));
		}
		return Database.query(query.toSOQL());
	}
}