src/objects/CBModelingLine__c.object
<CustomObject>
    <description>Mapping one object field to another</description>
    <fields>
        <fullName>CBModelingRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Modeling Rule</label>
        <referenceTo>CBModelingRule__c</referenceTo>
        <relationshipLabel>CB Modeling Lines</relationshipLabel>
        <relationshipName>CBModelingLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <label>Default</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultFieldFrom__c</fullName>
        <defaultValue>&apos;Parent&apos;</defaultValue>
        <label>Result Field From</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ResultField__c</fullName>
        <label>Result Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultObjectType__c</fullName>
        <label>Result Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceFieldFrom__c</fullName>
        <defaultValue>&apos;Parent&apos;</defaultValue>
        <label>Source Field From</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SourceField__c</fullName>
        <label>Source Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceObjectType__c</fullName>
        <label>Source Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpecifyDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SpecifyDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isGlobal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Global</label>
        <type>Checkbox</type>
    </fields>
    <label>CB Modeling Line</label>
    <nameField>
        <label>CB Modeling Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBModelingRule__c.object
<CustomObject>
    <description>Rule for converting one data type to another</description>
    <fields>
        <fullName>ResultRecordChildType__c</fullName>
        <label>Result Record Child Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultRecordParentType__c</fullName>
        <label>Result Record Parent Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceRecordChildType__c</fullName>
        <label>Source Record Child Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceRecordParentType__c</fullName>
        <description>The name of the source sObject type</description>
        <label>Source Record Parent Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CB Modeling Rule</label>
    <nameField>
        <label>CB Modeling Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Modeling Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBModelingLineSelector.cls
/** 
Created by Alex JR on 10/23/2021.
Copyright (c) 2021, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

Selector for the ModelingLine sObject
 */
public with sharing class CBModelingLineSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
				CBModelingLine__c.Id,
				CBModelingLine__c.Name,
				CBModelingLine__c.CBModelingRule__c,
				CBModelingLine__c.SourceField__c,
				CBModelingLine__c.SourceFieldFrom__c,
				CBModelingLine__c.ResultField__c,
				CBModelingLine__c.ResultFieldFrom__c,
				CBModelingLine__c.Default__c,
				CBModelingLine__c.SpecifyDefault__c,
				CBModelingLine__c.Type__c,
				CBModelingLine__c.isGlobal__c,
				CBModelingLine__c.SourceObjectType__c,
				CBModelingLine__c.ResultObjectType__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return CBModelingLine__c.sObjectType;
	}

	public override String getOrderBy() {
		return 'Name';
	}

	public List<CBModelingLine__c> getModelingLineById(String recordId) {
		fflib_QueryFactory query = newQueryFactory();
		if (!String.isBlank(recordId)) {
			query.setCondition('Id = \'' + recordId + '\'');
		}
		return Database.query(query.toSOQL());
	}

	public List<CBModelingLine__c> getModelingLinesByRule(String recordId) {
		fflib_QueryFactory query = newQueryFactory();
		if (!String.isBlank(recordId)) {
			query.setCondition('cblight__CBModelingRule__c = \'' + recordId + '\'');
		}
		return Database.query(query.toSOQL());
	}

	public List<CBModelingLine__c> getModelingLinesByRuleSet(Set<String> recordIdSet) {
		fflib_QueryFactory query = newQueryFactory();
		if (recordIdSet.size() > 0) {
			query.setCondition(
					' cblight__CBModelingRule__c IN ' + CBUtils.getFormattedINQuery(recordIdSet)
			);
		}
		return Database.query(query.toSOQL());
	}

	public List<CBModelingLine__c> getGlobalModelingLinesByModelingRule(String mrId) {
		CBModelingRule__c mr = new CBModelingRuleSelector().getModelingRuleById(mrId);
		fflib_QueryFactory query = newQueryFactory();
		String condition = ' cblight__isGlobal__c = true AND ' +
				'(cblight__SourceObjectType__c = \'' + mr.SourceRecordParentType__c + '\' OR cblight__SourceObjectType__c = \'' + mr.SourceRecordChildType__c + '\' ) ' +
				'AND ' +
				'(cblight__ResultObjectType__c = \'' + mr.ResultRecordParentType__c + '\' OR cblight__ResultObjectType__c = \'' + mr.ResultRecordChildType__c + '\' ) ';
		query.setCondition(condition);
		return Database.query(query.toSOQL());
	}
}