src/objects/CBPeriod__c.object
<CustomObject>
    <label>CB Period</label>
    <nameField>
        <label>CB Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBReport__c.object
<CustomObject>
    <label>CB Report</label>
    <nameField>
        <label>CB Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBReportColumn__c.object
<CustomObject>
    <fields>
        <fullName>CBPeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Period</label>
        <referenceTo>CBPeriod__c</referenceTo>
        <relationshipLabel>CB Report Columns</relationshipLabel>
        <relationshipName>CB_Report_Columns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBReport__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CB Report</label>
        <referenceTo>CBReport__c</referenceTo>
        <relationshipLabel>CB Report Columns</relationshipLabel>
        <relationshipName>CBReportColumns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBStyle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Style</label>
        <referenceTo>CBStyle__c</referenceTo>
        <relationshipLabel>CB Report Columns</relationshipLabel>
        <relationshipName>CB_Report_Columns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Color__c</fullName>
        <defaultValue>&apos;white&apos;</defaultValue>
        <label>Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formula__c</fullName>
        <description>Formula columns to calculate some values. For example: $1 * $2 / 2</description>
        <inlineHelpText>Formula columns to calculate some values. For example: $1 * $2 / 2</inlineHelpText>
        <label>Formula</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MasterColumn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Column</label>
        <referenceTo>CBReportColumn__c</referenceTo>
        <relationshipLabel>Master Columns</relationshipLabel>
        <relationshipName>MasterColumns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NeedYTD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need YTD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Master</fullName>
                    <default>true</default>
                    <label>Master</label>
                </value>
                <value>
                    <fullName>Simple</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Total</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <defaultValue>&apos;$&apos;</defaultValue>
        <label>Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValueField__c</fullName>
        <label>Value Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isHidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Hidden</label>
        <type>Checkbox</type>
    </fields>
    <label>CB Report Column</label>
    <nameField>
        <label>CB Report Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Report Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBStyle__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Text Color</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CB Style</label>
    <nameField>
        <label>CBStyle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CBReportColumnSelector.cls
/**
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

 */
public with sharing class CBReportColumnSelector extends fflib_SObjectSelector {

	private fflib_QueryFactory qFactory = newQueryFactory();

	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
				CBReportColumn__c.Id,
				CBReportColumn__c.Name,
				CBReportColumn__c.Color__c,
				CBReportColumn__c.Formula__c,
				CBReportColumn__c.ValueField__c,
				CBReportColumn__c.Type__c,
				CBReportColumn__c.MasterColumn__c,
				CBReportColumn__c.NeedYTD__c,
				CBReportColumn__c.isHidden__c,
				CBReportColumn__c.OrderNumber__c,
				CBReportColumn__c.CBPeriod__c,
				CBReportColumn__c.CBStyle__c,
				CBReportColumn__c.Unit__c,
				CBReportColumn__c.CBReport__c
		};
	}

	public override String getOrderBy() {
		return 'cblight__OrderNumber__c';
	}

	public Schema.SObjectType getSObjectType() {
		return CBReportColumn__c.sObjectType;
	}

	/**
	 * @param limitCounter if not null and > 0 causes a LIMIT clause to be added to the resulting query.
	 *
	 * @return instance of CBReportColumnSelector
	 */
	public CBReportColumnSelector setLimit(Integer limitCounter){
		if(limitCounter != null && limitCounter > 0) {
			qFactory.setLimit(limitCounter);
		}
		return this;
	}

	/**
	 * @param filter Sets the WHERE clause to the string provided. Do not include the "WHERE"
	 *
	 * @return instance of CBReportColumnSelector
	 */
	public CBReportColumnSelector setFilter(String filter){
		if (!String.isBlank(filter)) {
			qFactory.setCondition(filter);
		}
		return this;
	}

	public List<CBReportColumn__c> getReportColumnsByReportId(String reportId) {
		if (String.isBlank(reportId)) {
			return null;
		}
		fflib_QueryFactory query = newQueryFactory();
		query.selectField('cblight__CBPeriod__r.Name');
		query.selectField('cblight__CBStyle__r.Name');
		query.setCondition(' cblight__CBReport__c = \'' + reportId + '\' ');
		return Database.query(query.toSOQL());
	}

	/**
	 * @return List<CBReportColumn__c>: List of the records
	 */
	public List<CBReportColumn__c> query() {
		return Database.query(qFactory.toSOQL());
	}
}